### ISSUE TITLE
Player must be upgradable

### ISSUE THREAD

**Issue by marujalua** [MarcosChevis/alien-invaded#25]

**Comment by marujalua** [comment]
## Description
When a player kill a certain quantity of enemies he should receive a random upgrade, this upgrades should warn the UI Layer so it can show the upgrade. The quantity of enemies increases when the player receive an upgrade.

## Tasks
- [x] Attack Speed Upgrade
- [x] Attack Damage Upgrade
- [x] Life Upgrade
- [ ] Defense Upgrade
- [x] Speed Upgrade
- [ ] Elemental Upgrade (fire and ice)
- [x] Integrate Player with UI Layer
- [x] store numeric variables that control player behavior in the PlayerData struct

**Comment by marujalua** [comment]
@ThaisBras lembra de marcar quais Tasks você concluiu dessa Issue depois.
