### ISSUE TITLE
Make Room Teleport Animation

### ISSUE THREAD

**Issue by marujalua** [MarcosChevis/alien-invaded#42]
## Description
The Player should animate when teleporting

##Tasks
- [ ] Define room Teleport animation
- [ ] Implement room teleport animation
- [ ] make teleport assets
- [ ] update decoration schema to receive an assetName
